# Generated by Django 4.2.16 on 2026-01-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_key_columns', models.JSONField()),
                ('target_key_columns', models.JSONField()),
                ('compare_columns', models.JSONField()),
                ('fuzzy_match', models.BooleanField(default=False)),
                ('fuzzy_threshold', models.IntegerField(default=80)),
                ('results', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_reconciliations', to='datasets.dataset')),
                ('target_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_reconciliations', to='datasets.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
